### PR TITLE
Added .net standard target project; Small fix on test name

### PR DESCRIPTION
**Pull request by winterdouglas**
This adds support for .net standard, it's just a matter of publishing the package to the repositories.

### CODE REVIEW

**Comment by winterdouglas** [comment]
The build is failing on appveyor due to the old MSBuild version there, it should be updated to the latest version.

**Comment by mrstebo** [comment]
Nice work @winterdouglas 👍 

Could you update the AppVeyor file to Visual Studio 2017? I think that might do the trick.

Also, if we are supporting .NET standard then we may as well recreate the test project using the same framework so you can run the tests if you are making changes on a non-Windows OS. What do you think? 🤔 

And I have noticed the diff for the tests is quite large...are you using VSCode by any chance? 😅

**Comment by winterdouglas** [comment]
Hi @mrstebo.

Yep, I can update the AppVeyor file. Honestly, I've never worked with that before so I didn't know that there was a config file to look at :P
Regarding the tests, of course it's a good idea to do that, will do.

Sorry for the large diff, I'm gonna revert it and align with the rest. I use VS2017 on Windows normally but I can use code too.

**Comment by mrstebo** [comment]
I don't use VSCode. I thought you were using it 😅. Keep using Visual Studio please 🙌.

I use AppVeyor for anything that needs anything Windows-y. Works a treat 😎

**Comment by winterdouglas** [comment]
:)

Question, do you have plans to continue supporting PCL versions since .NET Standard is the replacement for PCL projects? I was trying to find a way here to migrate the PCL project to the new VS2017 format, at least to get rid of that packages.config but I couldn't find a way to do it, idk whether it's possible.

I have some wip on this and will probably update my PR later, in the worst case tomorrow.

**Comment by mrstebo** [comment]
Might as well continue supporting PCL. It uses the same code so I don't think there is any reason not to 😄

**Comment by winterdouglas** [comment]
Sorry for the late response but I'm traveling these days involved with some work things :(

I just updated the PR with some changes.
When I mentioned that PCL removal I was thinking on instead of having a different project for each target, to take advantage of the multi targeting and just have one project targeting different platforms, this is now possible and is much more clear as solution. With the targets that I currently set it is supposed to still support the same things as before: I'm targeting .net standard 1.1 (which is equivalent to the original PCL profile 7 if I understood correctly) and .net framework 4.5. I couldn't check whether it's working on all the targets that it's supposed to work with but I tested it on a bunch of them: .net standard, xamarin ios, xamarin android, uwp, .net framework 4.7.2 and .net core 2.1 and it works well.
I took these two links as guides for what I did:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
https://docs.microsoft.com/en-us/dotnet/standard/frameworks

I updated the AppVeyor script to use VS 2017 image and also to use the msbuild pack target to create the nuget package.

If you are approving this after your review/tests idk what to do with the version number considering it's a "major" thing and the ".Portable" package wouldn't be updated anymore on nuget.org but it would be part of the same "SnakeCase.JsonNet" package. I'd say it should be increased to 2.0, what do you think?

**Comment by mrstebo** [comment]
Nice work. I'll take a closer look when I am in the office.
Perhaps we could add some deprecation messages onto the Portable package before completely removing it from the solution.

**Comment by mrstebo** [comment]
Nice one. Maybe we should add a depreciation message for the portable library to let users know that they can use the standard library. What do you think?

**Comment by winterdouglas** [comment]
Done. Updated readme as well as set the original profile to 7 on the PCL project.

**Comment by mrstebo** [comment]
Nice! Do you know if there is a way for a message to appear if they install the portable library that lets them know to use the standard one? I'm not able to fully investigate at the moment 😅

**Comment by winterdouglas** [comment]
It's possible to set a message on the description of the package, what do you think?

**Comment by mrstebo** [comment]
@winterdouglas that sounds like a good idea, and it is what I have seen suggested too.
So we can add the message to the description, and then just make sure that the package isn't listed anymore when someone does a search 👍

**Comment by winterdouglas** [comment]
I will take a look at this tonight probably, will let you know :)
Thanks.

**Comment by winterdouglas** [comment]
Hello.
Have you seen my latest commit? I suppose that sets the deprecated message on nuget for the portable project. Can you check if everything is ok or if you think other changes are necessary?
Thanks.

**Comment by mrstebo** [comment]
Looks good to me! Thanks @winterdouglas 👍

**Pull request merged**
